# Site settings
title:       Paulo Roberto
email:       paulo.pinda@gmail.com
author:      Paulo Roberto Silva
description: "Blog sobre desenvolvimento de software e outros assuntos."
baseurl:     ""
url:         "https://opaulo.dev"
date_format: "%b %-d, %Y"
header_pages:
 - about.md
 - contact.html

google_analytics:

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true

# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Disqus post comments
disqus_shortname:

# Social icons
github_username: 0p4ul0
twitter_username: 0p4ul0
linkedin_username: 0p4ul0

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

text:
  pagination:
    newer: 'Novo'
    older: 'Antigo'
  share_buttons:
    text:         'Compartilhe:'
    facebook:     'Compartilhe no Facebook'
    twitter:      'Compartilhe no Twitter'
    googleplus:   'Compartilhe no Google+'
    linkedin:     'Compartilhe no LinkedIn'
    digg:         'Compartilhe no Digg'
    tumblr:       'Compartilhe no Tumblr'
    reddit:       'Compartilhe no Reddit'
    stumbleupon:  'Compartilhe no StumbleUpon'
    hackernews:   'Compartilhe no Hacker News'
  post:
    updated:        'Atualizado'
    minute_read:    'minuto(s) de leitura'
    related_posts:  'Posts relacionado'
    post_footer:    ''
  index:
    coming_soon: 'Em breve'
  og_locale: 'pt_BR'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    :title
paginate:     4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
