# Site settings
title:       Mixyll
email:       hello@saikiransripada.com
author:      Sai Kiran Sripada
description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
baseurl:     ""
url:         "https://mixyll.saikiransripada.com"
date_format: "%b %-d, %Y"
header_pages:
 - about.md
 - contact.html

google_analytics:

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true

# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Disqus post comments
disqus_shortname:

# Social icons
github_username: saikiransripada
twitter_username: wp_user
linkedin_username: saikiransripada
dev_username: dev_user

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share:'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
    post_footer:    'Lorem ipsum'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    :title
paginate:     4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
